// convex/seedDrinks.ts
import { mutation } from "./_generated/server";

export const seedAllDrinks = mutation({
  handler: async (ctx) => {
    const drinks = [
      // HOT COFFEE - Espresso Based
      {
        name: "Espresso",
        nameArabic: "اسبريسو",
        category: "hot_coffee",
        subcategory: "espresso_based",
        temperature: "hot",
        caffeineLevel: "high",
        sweetnessLevel: 0,
        vegan: true,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: false, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["focused", "energetic", "productive"],
        bestForWeather: ["cold", "cool"],
        bestTimeOfDay: ["morning", "afternoon"],
        flavorProfile: ["bitter", "strong", "bold"],
        intensity: 5
      },
      {
        name: "Ristretto",
        nameArabic: "ريستريتو",
        category: "hot_coffee",
        subcategory: "espresso_based",
        temperature: "hot",
        caffeineLevel: "high",
        sweetnessLevel: 0,
        vegan: true,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: false, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["focused", "energetic"],
        bestForWeather: ["cold", "cool"],
        bestTimeOfDay: ["morning"],
        flavorProfile: ["intense", "concentrated", "bold"],
        intensity: 5
      },
      {
        name: "Macchiato",
        nameArabic: "ماكياتو",
        category: "hot_coffee",
        subcategory: "espresso_based",
        temperature: "hot",
        caffeineLevel: "high",
        sweetnessLevel: 2,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["focused", "calm"],
        bestForWeather: ["cold", "cool"],
        bestTimeOfDay: ["morning", "afternoon"],
        flavorProfile: ["creamy", "strong", "balanced"],
        intensity: 4
      },
      {
        name: "Espresso Con Panna",
        nameArabic: "كونبانا اسبريسو",
        category: "hot_coffee",
        subcategory: "espresso_based",
        temperature: "hot",
        caffeineLevel: "high",
        sweetnessLevel: 3,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["indulgent", "relaxed"],
        bestForWeather: ["cold"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["creamy", "sweet", "bold"],
        intensity: 4
      },
      {
        name: "Americano",
        nameArabic: "أمريكانو",
        category: "hot_coffee",
        subcategory: "espresso_based",
        temperature: "hot",
        caffeineLevel: "high",
        sweetnessLevel: 0,
        vegan: true,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: false, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["focused", "productive", "energetic"],
        bestForWeather: ["cold", "cool", "rainy"],
        bestTimeOfDay: ["morning", "afternoon"],
        flavorProfile: ["smooth", "mild", "balanced"],
        intensity: 3
      },
      {
        name: "Cappuccino",
        nameArabic: "كابتشينو",
        category: "hot_coffee",
        subcategory: "espresso_based",
        temperature: "hot",
        caffeineLevel: "medium",
        sweetnessLevel: 3,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["happy", "relaxed", "social"],
        bestForWeather: ["cold", "cool"],
        bestTimeOfDay: ["morning", "afternoon"],
        flavorProfile: ["creamy", "smooth", "balanced"],
        intensity: 3
      },
      {
        name: "Latte",
        nameArabic: "لاتيه",
        category: "hot_coffee",
        subcategory: "latte",
        temperature: "hot",
        caffeineLevel: "medium",
        sweetnessLevel: 4,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["calm", "relaxed", "comfortable"],
        bestForWeather: ["cold", "cool"],
        bestTimeOfDay: ["morning", "afternoon", "evening"],
        flavorProfile: ["creamy", "mild", "smooth"],
        intensity: 2
      },
      {
        name: "Caramel Macchiato",
        nameArabic: "كراميل ماكياتو",
        category: "hot_coffee",
        subcategory: "specialty",
        temperature: "hot",
        caffeineLevel: "medium",
        sweetnessLevel: 7,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["happy", "indulgent", "relaxed"],
        bestForWeather: ["cold"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["sweet", "creamy", "caramel"],
        intensity: 2
      },
      {
        name: "Cinnamon Latte",
        nameArabic: "لاتيه قرفة",
        category: "hot_coffee",
        subcategory: "specialty",
        temperature: "hot",
        caffeineLevel: "medium",
        sweetnessLevel: 6,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["cozy", "relaxed", "comfortable"],
        bestForWeather: ["cold"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["spicy", "sweet", "warm"],
        intensity: 3
      },
      {
        name: "Mocha",
        nameArabic: "موكا",
        category: "hot_coffee",
        subcategory: "specialty",
        temperature: "hot",
        caffeineLevel: "medium",
        sweetnessLevel: 7,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["indulgent", "happy", "comfort"],
        bestForWeather: ["cold", "rainy"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["chocolate", "sweet", "creamy"],
        intensity: 3
      },
      {
        name: "Flat White",
        nameArabic: "فلات وايت",
        category: "hot_coffee",
        subcategory: "espresso_based",
        temperature: "hot",
        caffeineLevel: "high",
        sweetnessLevel: 2,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["focused", "productive"],
        bestForWeather: ["cold", "cool"],
        bestTimeOfDay: ["morning"],
        flavorProfile: ["creamy", "strong", "velvety"],
        intensity: 4
      },
      {
        name: "White Mocha",
        nameArabic: "وايت موكا",
        category: "hot_coffee",
        subcategory: "specialty",
        temperature: "hot",
        caffeineLevel: "medium",
        sweetnessLevel: 8,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["indulgent", "happy"],
        bestForWeather: ["cold"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["white chocolate", "sweet", "creamy"],
        intensity: 2
      },
      {
        name: "Chai Latte",
        nameArabic: "تشاي لاتيه",
        category: "hot_coffee",
        subcategory: "specialty",
        temperature: "hot",
        caffeineLevel: "low",
        sweetnessLevel: 6,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["cozy", "relaxed", "warm"],
        bestForWeather: ["cold", "rainy"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["spicy", "sweet", "aromatic"],
        intensity: 3
      },

      // HOT CHOCOLATE
      {
        name: "Hot Chocolate",
        nameArabic: "هوت شوكلت",
        category: "hot_chocolate",
        temperature: "hot",
        caffeineLevel: "low",
        sweetnessLevel: 8,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["comfort", "cozy", "indulgent"],
        bestForWeather: ["cold", "rainy"],
        bestTimeOfDay: ["afternoon", "evening", "night"],
        flavorProfile: ["chocolate", "sweet", "rich"],
        intensity: 2
      },
      {
        name: "White Hot Chocolate",
        nameArabic: "وايت هوت شوكلت",
        category: "hot_chocolate",
        temperature: "hot",
        caffeineLevel: "none",
        sweetnessLevel: 9,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["indulgent", "happy", "comfort"],
        bestForWeather: ["cold"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["white chocolate", "sweet", "creamy"],
        intensity: 1
      },
      {
        name: "Toffee Cake Hot Chocolate",
        nameArabic: "توفي كيك هوت شوكلت",
        category: "hot_chocolate",
        temperature: "hot",
        caffeineLevel: "low",
        sweetnessLevel: 9,
        vegan: false,
        vegetarian: true,
        seasonal: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: true, sulphite: false, wheat: true, gluten: true, lupin: false },
        bestForMoods: ["indulgent", "festive", "happy"],
        bestForWeather: ["cold"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["toffee", "sweet", "dessert"],
        intensity: 2
      },

      // SHAKEN COFFEE (CORTO)
      {
        name: "Corto Black",
        nameArabic: "بلاك كورتو",
        category: "shaken_coffee",
        temperature: "hot",
        caffeineLevel: "high",
        sweetnessLevel: 0,
        vegan: false,
        vegetarian: true,
        allergens: { egg: true, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: true, gluten: true, lupin: false },
        bestForMoods: ["energetic", "focused"],
        bestForWeather: ["any"],
        bestTimeOfDay: ["morning", "afternoon"],
        flavorProfile: ["strong", "bold"],
        intensity: 5
      },
      {
        name: "Corto Classic",
        nameArabic: "كلاسيك كورتو",
        category: "shaken_coffee",
        temperature: "hot",
        caffeineLevel: "high",
        sweetnessLevel: 5,
        vegan: false,
        vegetarian: true,
        allergens: { egg: true, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: true, gluten: true, lupin: false },
        bestForMoods: ["happy", "energetic"],
        bestForWeather: ["any"],
        bestTimeOfDay: ["morning", "afternoon"],
        flavorProfile: ["balanced", "sweet", "smooth"],
        intensity: 4
      },
      {
        name: "Corto Mocha",
        nameArabic: "كورتو موكا",
        category: "shaken_coffee",
        temperature: "hot",
        caffeineLevel: "high",
        sweetnessLevel: 7,
        vegan: false,
        vegetarian: true,
        allergens: { egg: true, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: true, gluten: true, lupin: false },
        bestForMoods: ["indulgent", "energetic"],
        bestForWeather: ["any"],
        bestTimeOfDay: ["afternoon"],
        flavorProfile: ["chocolate", "sweet", "bold"],
        intensity: 4
      },
      {
        name: "Corto Caramel",
        nameArabic: "كراميل كورتو",
        category: "shaken_coffee",
        temperature: "hot",
        caffeineLevel: "high",
        sweetnessLevel: 8,
        vegan: false,
        vegetarian: true,
        allergens: { egg: true, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: true, gluten: true, lupin: false },
        bestForMoods: ["happy", "indulgent"],
        bestForWeather: ["any"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["caramel", "sweet", "smooth"],
        intensity: 3
      },

      // TEA
      {
        name: "Regular Tea",
        nameArabic: "شاي",
        category: "tea",
        temperature: "hot",
        caffeineLevel: "low",
        sweetnessLevel: 0,
        vegan: true,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: false, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["calm", "relaxed", "traditional"],
        bestForWeather: ["any"],
        bestTimeOfDay: ["morning", "afternoon", "evening"],
        flavorProfile: ["classic", "aromatic"],
        intensity: 2
      },
      {
        name: "Flavored Herbal Tea",
        nameArabic: "شاي بالأعشاب",
        category: "tea",
        temperature: "hot",
        caffeineLevel: "none",
        sweetnessLevel: 0,
        vegan: true,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: false, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["calm", "relaxed", "wellness"],
        bestForWeather: ["any"],
        bestTimeOfDay: ["afternoon", "evening", "night"],
        flavorProfile: ["herbal", "soothing"],
        intensity: 1
      },

      // COLD COFFEE
      {
        name: "Iced Espresso",
        nameArabic: "ايس اسبريسو",
        category: "cold_coffee",
        subcategory: "espresso_based",
        temperature: "cold",
        caffeineLevel: "high",
        sweetnessLevel: 0,
        vegan: true,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: false, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["energetic", "focused"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["morning", "afternoon"],
        flavorProfile: ["bold", "intense"],
        intensity: 5
      },
      {
        name: "Iced Americano",
        nameArabic: "ايس أمريكانو",
        category: "cold_coffee",
        subcategory: "espresso_based",
        temperature: "cold",
        caffeineLevel: "high",
        sweetnessLevel: 0,
        vegan: true,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: false, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["refreshed", "productive"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["morning", "afternoon"],
        flavorProfile: ["smooth", "clean"],
        intensity: 3
      },
      {
        name: "Iced Latte",
        nameArabic: "ايس لاتيه",
        category: "cold_coffee",
        subcategory: "latte",
        temperature: "cold",
        caffeineLevel: "medium",
        sweetnessLevel: 4,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["refreshed", "calm"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["morning", "afternoon", "evening"],
        flavorProfile: ["creamy", "smooth", "mild"],
        intensity: 2
      },
      {
        name: "Iced Macchiato",
        nameArabic: "ايس ماكياتو",
        category: "cold_coffee",
        subcategory: "specialty",
        temperature: "cold",
        caffeineLevel: "high",
        sweetnessLevel: 3,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["refreshed", "energetic"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["morning", "afternoon"],
        flavorProfile: ["layered", "creamy", "strong"],
        intensity: 4
      },
      {
        name: "Iced Caramel Macchiato",
        nameArabic: "ايس كراميل ماكياتو",
        category: "cold_coffee",
        subcategory: "specialty",
        temperature: "cold",
        caffeineLevel: "medium",
        sweetnessLevel: 7,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["happy", "indulgent"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["caramel", "sweet", "creamy"],
        intensity: 2
      },
      {
        name: "Iced Mocha",
        nameArabic: "ايس موكا",
        category: "cold_coffee",
        subcategory: "specialty",
        temperature: "cold",
        caffeineLevel: "medium",
        sweetnessLevel: 7,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["indulgent", "refreshed"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["chocolate", "sweet", "creamy"],
        intensity: 3
      },
      {
        name: "Iced Flat White",
        nameArabic: "ايس فلات وايت",
        category: "cold_coffee",
        subcategory: "espresso_based",
        temperature: "cold",
        caffeineLevel: "high",
        sweetnessLevel: 2,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: true, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["focused", "refreshed"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["morning", "afternoon"],
        flavorProfile: ["strong", "velvety", "creamy"],
        intensity: 4
      },
      {
        name: "Iced White Mocha",
        nameArabic: "ايس وايت موكا",
        category: "cold_coffee",
        subcategory: "specialty",
        temperature: "cold",
        caffeineLevel: "medium",
        sweetnessLevel: 8,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["indulgent", "happy"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["white chocolate", "sweet", "creamy"],
        intensity: 2
      },
      {
        name: "Iced Chocolate",
        nameArabic: "ايس شوكلت",
        category: "cold_chocolate",
        temperature: "cold",
        caffeineLevel: "low",
        sweetnessLevel: 8,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["indulgent", "refreshed", "happy"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["chocolate", "sweet", "creamy"],
        intensity: 2
      },
      {
        name: "Iced White Chocolate",
        nameArabic: "ايس وايت شوكلت",
        category: "cold_chocolate",
        temperature: "cold",
        caffeineLevel: "none",
        sweetnessLevel: 9,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["indulgent", "happy"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["white chocolate", "sweet", "creamy"],
        intensity: 1
      },

      // LEMONADE
      {
        name: "Classic Lemonade",
        nameArabic: "ليموناضة كلاسيك",
        category: "lemonade",
        temperature: "cold",
        caffeineLevel: "none",
        sweetnessLevel: 7,
        vegan: true,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: false, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["refreshed", "energetic", "happy"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["citrus", "tangy", "sweet"],
        intensity: 3
      },
      {
        name: "Peach Lemonade",
        nameArabic: "ليموناضة بالخوخ",
        category: "lemonade",
        temperature: "cold",
        caffeineLevel: "none",
        sweetnessLevel: 8,
        vegan: true,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: false, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["refreshed", "happy", "relaxed"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["fruity", "sweet", "citrus"],
        intensity: 2
      },
      {
        name: "Mint Lemonade",
        nameArabic: "ليموناضة بالنعناع",
        category: "lemonade",
        temperature: "cold",
        caffeineLevel: "none",
        sweetnessLevel: 7,
        vegan: true,
        vegetarian: true,
        allergens: {"egg":false,"fish":false,"shellfish":false,"milk":false,"peanuts":false,"treeNuts":false,"sesame":false,"celery":false,"mustard":false,"soy":false,"sulphite":false,"wheat":false,"gluten":false,"lupin":false},
        bestForMoods: ["refreshed","energetic","cool"],
        bestForWeather: ["hot","warm"],
        bestTimeOfDay: ["afternoon","evening"],
        flavorProfile: ["minty","citrus","refreshing"],
        intensity: 3
      },
      {
        name: "Strawberry Lemonade",
        nameArabic: "ليموناضة بالفراولة",
        category: "lemonade",
        temperature: "cold",
        caffeineLevel: "none",
        sweetnessLevel: 8,
        vegan: true,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: false, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["refreshed", "happy", "relaxed"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["fruity", "sweet", "citrus"],
        intensity: 2
      },

      // ICE TEA
      {
        name: "Lemon Ice Tea",
        nameArabic: "شاى مثلج",
        category: "ice_tea",
        temperature: "cold",
        caffeineLevel: "low",
        sweetnessLevel: 6,
        vegan: true,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: false, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["refreshed", "energetic", "cool"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["citrus", "refreshing", "tea"],
        intensity: 2
      },
      {
        name: "Peach Ice Tea",
        nameArabic: "شاى مثلج بالخوخ",
        category: "ice_tea",
        temperature: "cold",
        caffeineLevel: "low",
        sweetnessLevel: 7,
        vegan: true,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: false, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["refreshed", "happy", "relaxed"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["fruity", "sweet", "tea"],
        intensity: 2
      },
      {
        name: "Hibiscus Peach Ice Tea",
        nameArabic: "كدية و ليمونيد بالخوخ كركديه أيس تي",
        category: "ice_tea",
        temperature: "cold",
        caffeineLevel: "none",
        sweetnessLevel: 7,
        vegan: true,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: false, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["refreshed", "relaxed", "happy"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["floral", "fruity", "tangy"],
        intensity: 3
      },
      {
        name: "Babble Peach Ice Tea",
        nameArabic: "بابل ايس تي خوخ",
        category: "ice_tea",
        temperature: "cold",
        caffeineLevel: "low",
        sweetnessLevel: 7,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["fun", "happy", "refreshed"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["fruity", "sweet", "creamy"],
        intensity: 2
      },

      // FROSTINO/FRAPPE
      {
        name: "Mango Passion Fruit Frostino",
        nameArabic: "مانجو باشون",
        category: "frappe",
        temperature: "frozen",
        caffeineLevel: "none",
        sweetnessLevel: 8,
        vegan: true,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: false, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["tropical", "happy", "refreshed"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["fruity", "tropical", "tangy"],
        intensity: 3
      },
      {
        name: "Raspberry & Blackberry Frostino",
        nameArabic: "بالك بيري&راسبيري",
        category: "frappe",
        temperature: "frozen",
        caffeineLevel: "none",
        sweetnessLevel: 7,
        vegan: true,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: false, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["refreshed", "indulgent", "happy"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["berry", "tangy", "sweet"],
        intensity: 3
      },
      {
        name: "Chocolate Cream Frostino",
        nameArabic: "كريمة الشيكوالتة",
        category: "frappe",
        temperature: "frozen",
        caffeineLevel: "low",
        sweetnessLevel: 8,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["indulgent", "happy", "comfort"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["chocolate", "creamy", "sweet"],
        intensity: 2
      },
      {
        name: "Caramel Cream Frostino",
        nameArabic: "كريمة الكراميل",
        category: "frappe",
        temperature: "frozen",
        caffeineLevel: "low",
        sweetnessLevel: 8,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["indulgent", "happy", "sweet"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["caramel", "creamy", "sweet"],
        intensity: 2
      },
      {
        name: "Strawberry Frostino",
        nameArabic: "الفراولة",
        category: "frappe",
        temperature: "frozen",
        caffeineLevel: "none",
        sweetnessLevel: 8,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["happy", "refreshed", "fun"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["fruity", "sweet", "creamy"],
        intensity: 2
      },
      {
        name: "Coffee Cream Frostino",
        nameArabic: "كريمة القهوة",
        category: "frappe",
        temperature: "frozen",
        caffeineLevel: "medium",
        sweetnessLevel: 7,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["energetic", "indulgent", "cool"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon"],
        flavorProfile: ["coffee", "creamy", "sweet"],
        intensity: 3
      },
      {
        name: "Mocha Cream Frostino",
        nameArabic: "كريمة الموكا",
        category: "frappe",
        temperature: "frozen",
        caffeineLevel: "medium",
        sweetnessLevel: 8,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["indulgent", "energetic", "happy"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["chocolate", "coffee", "creamy"],
        intensity: 3
      },
      {
        name: "Chocolate Fudge Brownie Frappe",
        nameArabic: "شوكلت فدج براوني فرابيه",
        category: "frappe",
        temperature: "frozen",
        caffeineLevel: "low",
        sweetnessLevel: 9,
        vegan: false,
        vegetarian: true,
        allergens: { egg: true, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: true, sesame: false, celery: false, mustard: false, soy: true, sulphite: false, wheat: true, gluten: true, lupin: false },
        bestForMoods: ["indulgent", "decadent", "happy"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["chocolate", "rich", "dessert"],
        intensity: 2
      },
      {
        name: "Caramel Short Bread Frappe",
        nameArabic: "كراميل شورت بريد فرابية",
        category: "frappe",
        temperature: "frozen",
        caffeineLevel: "low",
        sweetnessLevel: 9,
        vegan: false,
        vegetarian: true,
        allergens: { egg: true, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: true, sesame: false, celery: false, mustard: false, soy: true, sulphite: false, wheat: true, gluten: true, lupin: false },
        bestForMoods: ["indulgent", "happy", "comfort"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["caramel", "buttery", "sweet"],
        intensity: 2
      },
      {
        name: "Blueberry Babble Frappe",
        nameArabic: "توت بابل فرابيه",
        category: "frappe",
        temperature: "frozen",
        caffeineLevel: "none",
        sweetnessLevel: 8,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["fun", "refreshed", "happy"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["berry", "sweet", "creamy"],
        intensity: 2
      },
      {
        name: "Mango Babble Frappe",
        nameArabic: "مانجو بابل فرابيه",
        category: "frappe",
        temperature: "frozen",
        caffeineLevel: "none",
        sweetnessLevel: 8,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["tropical", "happy", "refreshed"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["mango", "tropical", "creamy"],
        intensity: 2
      },
      {
        name: "Raspberry Babble Frappe",
        nameArabic: "توت بابل فرابيه",
        category: "frappe",
        temperature: "frozen",
        caffeineLevel: "none",
        sweetnessLevel: 8,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["fun", "happy", "refreshed"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["berry", "tangy", "creamy"],
        intensity: 2
      },
      {
        name: "Acai Frappe",
        nameArabic: "اسيه فرابيه",
        category: "frappe",
        temperature: "frozen",
        caffeineLevel: "none",
        sweetnessLevel: 7,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["wellness", "energetic", "refreshed"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["morning", "afternoon"],
        flavorProfile: ["berry", "antioxidant", "refreshing"],
        intensity: 3
      },
      {
        name: "Mango Frappe",
        nameArabic: "مانجو فرابيه",
        category: "frappe",
        temperature: "frozen",
        caffeineLevel: "none",
        sweetnessLevel: 8,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["tropical", "happy", "refreshed"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["mango", "tropical", "sweet"],
        intensity: 2
      },
      {
        name: "Toffee Cake Frappe",
        nameArabic: "توفي كيك فرابيه",
        category: "frappe",
        temperature: "frozen",
        caffeineLevel: "low",
        sweetnessLevel: 9,
        vegan: false,
        vegetarian: true,
        seasonal: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: true, sulphite: false, wheat: true, gluten: true, lupin: false },
        bestForMoods: ["indulgent", "festive", "happy"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["toffee", "sweet", "dessert"],
        intensity: 2
      },
      {
        name: "Maple Nut Frappe",
        nameArabic: "مابل نت فرابية",
        category: "frappe",
        temperature: "frozen",
        caffeineLevel: "low",
        sweetnessLevel: 8,
        vegan: false,
        vegetarian: true,
        allergens: { egg: true, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: true, sesame: false, celery: false, mustard: false, soy: true, sulphite: false, wheat: true, gluten: true, lupin: false },
        bestForMoods: ["indulgent", "cozy", "happy"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["maple", "nutty", "sweet"],
        intensity: 3
      },

      // REFRESHERS
      {
        name: "Hot Refresher",
        nameArabic: "هوت ريفريشر",
        category: "refresher",
        temperature: "hot",
        caffeineLevel: "none",
        sweetnessLevel: 5,
        vegan: true,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: false, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["energetic", "refreshed", "wellness"],
        bestForWeather: ["cold", "cool"],
        bestTimeOfDay: ["morning", "afternoon"],
        flavorProfile: ["herbal", "citrus", "refreshing"],
        intensity: 2
      },
      {
        name: "Strawberry & Apple Aloe Vera Refresher",
        nameArabic: "شراب الصبار مع التفاح والفراولة",
        category: "refresher",
        temperature: "cold",
        caffeineLevel: "none",
        sweetnessLevel: 6,
        vegan: true,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: false, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["wellness", "refreshed", "healthy"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["morning", "afternoon"],
        flavorProfile: ["fruity", "refreshing", "light"],
        intensity: 2
      },
      {
        name: "Blueberry Refresher",
        nameArabic: "ريفريشر توت",
        category: "refresher",
        temperature: "cold",
        caffeineLevel: "none",
        sweetnessLevel: 6,
        vegan: true,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: false, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["refreshed", "energetic", "wellness"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["morning", "afternoon"],
        flavorProfile: ["berry", "refreshing", "light"],
        intensity: 2
      },
      {
        name: "Peach Refresher",
        nameArabic: "ريفريشر خوخ",
        category: "refresher",
        temperature: "cold",
        caffeineLevel: "none",
        sweetnessLevel: 6,
        vegan: true,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: false, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["refreshed", "happy", "light"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["morning", "afternoon"],
        flavorProfile: ["fruity", "refreshing", "light"],
        intensity: 2
      },

      // SPECIALTY/CAMPAIGN DRINKS
      {
        name: "Iced Matcha Coconut",
        nameArabic: "كوكونت ايس ماتشا",
        category: "cold_coffee",
        subcategory: "specialty",
        temperature: "cold",
        caffeineLevel: "medium",
        sweetnessLevel: 6,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: true, lupin: false },
        bestForMoods: ["focused", "wellness", "calm"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["morning", "afternoon"],
        flavorProfile: ["matcha", "coconut", "earthy"],
        intensity: 3
      },
      {
        name: "Coconut Matcha",
        nameArabic: "كوكونت ماتشا",
        category: "hot_coffee",
        subcategory: "specialty",
        temperature: "hot",
        caffeineLevel: "medium",
        sweetnessLevel: 6,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: true, lupin: false },
        bestForMoods: ["focused", "wellness", "calm"],
        bestForWeather: ["cold", "cool"],
        bestTimeOfDay: ["morning", "afternoon"],
        flavorProfile: ["matcha", "coconut", "earthy"],
        intensity: 3
      },
      {
        name: "Gingerbread Latte",
        nameArabic: "جينجر بريد لاتيه",
        category: "hot_coffee",
        subcategory: "specialty",
        temperature: "hot",
        caffeineLevel: "medium",
        sweetnessLevel: 7,
        vegan: false,
        vegetarian: true,
        seasonal: true,
        allergens: { egg: true, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: true, sesame: false, celery: false, mustard: false, soy: true, sulphite: false, wheat: true, gluten: true, lupin: false },
        bestForMoods: ["festive", "cozy", "warm"],
        bestForWeather: ["cold"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["ginger", "spicy", "sweet"],
        intensity: 3
      },
      {
        name: "Iced Toffee Cake Latte",
        nameArabic: "ايس توفي كيك لاتيه",
        category: "cold_coffee",
        subcategory: "specialty",
        temperature: "cold",
        caffeineLevel: "medium",
        sweetnessLevel: 8,
        vegan: false,
        vegetarian: true,
        seasonal: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: true, sulphite: false, wheat: true, gluten: true, lupin: false },
        bestForMoods: ["indulgent", "festive", "happy"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["toffee", "sweet", "dessert"],
        intensity: 2
      },
      {
        name: "Toffee Cake Latte",
        nameArabic: "توفي كيك لاتيه",
        category: "hot_coffee",
        subcategory: "specialty",
        temperature: "hot",
        caffeineLevel: "medium",
        sweetnessLevel: 8,
        vegan: false,
        vegetarian: true,
        seasonal: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: true, sulphite: false, wheat: true, gluten: true, lupin: false },
        bestForMoods: ["indulgent", "festive", "cozy"],
        bestForWeather: ["cold"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["toffee", "sweet", "dessert"],
        intensity: 2
      },
      {
        name: "Salted Caramel Cappuccino",
        nameArabic: "سولتيد كراميل كابتشينو",
        category: "hot_coffee",
        subcategory: "specialty",
        temperature: "hot",
        caffeineLevel: "medium",
        sweetnessLevel: 7,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["indulgent", "happy", "comfort"],
        bestForWeather: ["cold", "cool"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["caramel", "salty", "sweet"],
        intensity: 3
      },
      {
        name: "Iced Salted Caramel Cappuccino",
        nameArabic: "أيس سولتيد كراميل كابتشينو",
        category: "cold_coffee",
        subcategory: "specialty",
        temperature: "cold",
        caffeineLevel: "medium",
        sweetnessLevel: 7,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["indulgent", "happy", "refreshed"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["caramel", "salty", "sweet"],
        intensity: 3
      },
      {
        name: "Spanish Flat White",
        nameArabic: "سبانش فلات وايت",
        category: "hot_coffee",
        subcategory: "espresso_based",
        temperature: "hot",
        caffeineLevel: "high",
        sweetnessLevel: 3,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["focused", "productive", "energetic"],
        bestForWeather: ["cold", "cool"],
        bestTimeOfDay: ["morning", "afternoon"],
        flavorProfile: ["strong", "creamy", "condensed milk"],
        intensity: 4
      },
      {
        name: "Iced Spanish Flat White",
        nameArabic: "أيس سبانش فلات وايت",
        category: "cold_coffee",
        subcategory: "espresso_based",
        temperature: "cold",
        caffeineLevel: "high",
        sweetnessLevel: 3,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["focused", "refreshed", "energetic"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["morning", "afternoon"],
        flavorProfile: ["strong", "creamy", "condensed milk"],
        intensity: 4
      },
      {
        name: "Iced Vanilla And Hazelnut Latte",
        nameArabic: "فانيليا أند هازلنت لاتيه",
        category: "cold_coffee",
        subcategory: "specialty",
        temperature: "cold",
        caffeineLevel: "medium",
        sweetnessLevel: 7,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: true, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["happy", "indulgent", "refreshed"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["vanilla", "hazelnut", "sweet"],
        intensity: 2
      },
      {
        name: "Vanilla And Hazelnut Latte",
        nameArabic: "أيس فانيليا أند هازلنت لاتيه",
        category: "hot_coffee",
        subcategory: "specialty",
        temperature: "hot",
        caffeineLevel: "medium",
        sweetnessLevel: 7,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: true, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["happy", "indulgent", "cozy"],
        bestForWeather: ["cold", "cool"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["vanilla", "hazelnut", "sweet"],
        intensity: 2
      },
      {
        name: "Pistachio Corto",
        nameArabic: "كورتو بستاشيو",
        category: "shaken_coffee",
        temperature: "hot",
        caffeineLevel: "high",
        sweetnessLevel: 7,
        vegan: false,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: true, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["indulgent", "energetic", "unique"],
        bestForWeather: ["any"],
        bestTimeOfDay: ["afternoon"],
        flavorProfile: ["pistachio", "nutty", "sweet"],
        intensity: 4
      },
      {
        name: "Maple Nut Latte",
        nameArabic: "مابل نت لاتيه",
        category: "hot_coffee",
        subcategory: "specialty",
        temperature: "hot",
        caffeineLevel: "medium",
        sweetnessLevel: 8,
        vegan: false,
        vegetarian: true,
        allergens: { egg: true, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: true, sesame: false, celery: false, mustard: false, soy: true, sulphite: false, wheat: true, gluten: true, lupin: false },
        bestForMoods: ["indulgent", "cozy", "comfort"],
        bestForWeather: ["cold"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["maple", "nutty", "sweet"],
        intensity: 3
      },
      {
        name: "Iced Maple Nut Latte",
        nameArabic: "أيس مابل نت لاتيه",
        category: "cold_coffee",
        subcategory: "specialty",
        temperature: "cold",
        caffeineLevel: "medium",
        sweetnessLevel: 8,
        vegan: false,
        vegetarian: true,
        allergens: { egg: true, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: true, sesame: false, celery: false, mustard: false, soy: true, sulphite: false, wheat: true, gluten: true, lupin: false },
        bestForMoods: ["indulgent", "refreshed", "happy"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["maple", "nutty", "sweet"],
        intensity: 3
      },
      {
        name: "Spanish Maple Nut Latte",
        nameArabic: "سبانش مابل نت لاتيه",
        category: "hot_coffee",
        subcategory: "specialty",
        temperature: "hot",
        caffeineLevel: "medium",
        sweetnessLevel: 8,
        vegan: false,
        vegetarian: true,
        allergens: { egg: true, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: true, sesame: false, celery: false, mustard: false, soy: true, sulphite: false, wheat: true, gluten: true, lupin: false },
        bestForMoods: ["indulgent", "cozy", "unique"],
        bestForWeather: ["cold"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["maple", "nutty", "condensed milk"],
        intensity: 3
      },
      {
        name: "Iced Spanish Maple Nut Latte",
        nameArabic: "أيس سبانش مابل نت لاتيه",
        category: "cold_coffee",
        subcategory: "specialty",
        temperature: "cold",
        caffeineLevel: "medium",
        sweetnessLevel: 8,
        vegan: false,
        vegetarian: true,
        allergens: { egg: true, fish: false, shellfish: false, milk: true, peanuts: false, treeNuts: true, sesame: false, celery: false, mustard: false, soy: true, sulphite: false, wheat: true, gluten: true, lupin: false },
        bestForMoods: ["indulgent", "refreshed", "unique"],
        bestForWeather: ["hot", "warm"],
        bestTimeOfDay: ["afternoon", "evening"],
        flavorProfile: ["maple", "nutty", "condensed milk"],
        intensity: 3
      },

      // ALTERNATIVE MILK
      {
        name: "Soya Milk",
        nameArabic: "لبن الصويا",
        category: "alternative_milk",
        temperature: "any",
        caffeineLevel: "none",
        sweetnessLevel: 2,
        vegan: true,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: false, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: true, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["wellness", "vegan"],
        bestForWeather: ["any"],
        bestTimeOfDay: ["any"],
        flavorProfile: ["mild", "plant-based"],
        intensity: 1
      },
      {
        name: "Oat Milk",
        nameArabic: "لبن الشوفان",
        category: "alternative_milk",
        temperature: "any",
        caffeineLevel: "none",
        sweetnessLevel: 3,
        vegan: true,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: false, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["wellness", "vegan"],
        bestForWeather: ["any"],
        bestTimeOfDay: ["any"],
        flavorProfile: ["creamy", "oat", "plant-based"],
        intensity: 1
      },
      {
        name: "Coconut Milk",
        nameArabic: "لبن جوز الهند",
        category: "alternative_milk",
        temperature: "any",
        caffeineLevel: "none",
        sweetnessLevel: 3,
        vegan: true,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: false, peanuts: false, treeNuts: false, sesame: false, celery: false, mustard: false, soy: true, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["tropical", "wellness", "vegan"],
        bestForWeather: ["any"],
        bestTimeOfDay: ["any"],
        flavorProfile: ["coconut", "tropical", "plant-based"],
        intensity: 2
      },
      {
        name: "Almond Milk",
        nameArabic: "لبن اللوز",
        category: "alternative_milk",
        temperature: "any",
        caffeineLevel: "none",
        sweetnessLevel: 2,
        vegan: true,
        vegetarian: true,
        allergens: { egg: false, fish: false, shellfish: false, milk: false, peanuts: false, treeNuts: true, sesame: false, celery: false, mustard: false, soy: false, sulphite: false, wheat: false, gluten: false, lupin: false },
        bestForMoods: ["wellness", "vegan"],
        bestForWeather: ["any"],
        bestTimeOfDay: ["any"],
        flavorProfile: ["nutty", "mild", "plant-based"],
        intensity: 1
      }
    ];

    // Insert all drinks into the database
    for (const drink of drinks) {
      await ctx.db.insert("drinks", drink);
    }

    return { message: `Successfully seeded ${drinks.length} drinks!` };
  },
});